version: '3.8'

services:
  speaksense:
    build:
      context: .
      dockerfile: dockerfile.cuda
      args:
        - FEATURES=cuda
    image: speaksense:cuda
    container_name: speaksense-asr
    restart: unless-stopped
    ports:
      - "7200:7200"  # REST API
      - "7300:7300"  # gRPC
    volumes:
      - ./models:/app/models
      - ./asr_data:/app/asr_data
    environment:
      - ASR_SQLITE_PATH=sqlite:///app/asr_data/database/storage.db?mode=rwc
      - ASR_AUDIO_PATH=/app/asr_data/audio
      - ASR_MODEL_PATH=/app/models/ggml-large-v3.bin
      - RUST_LOG=info
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]  
    runtime: nvidia

  # optional: if using etcd
  etcd:
    image: bitnami/etcd:latest
    container_name: speaksense-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/bitnami/etcd

volumes:
  etcd_data:
    driver: local 